#include "rsa.h"


/*
A few details:
- The public exponent is by default set to 65537, you can indicate your at condition to respect the following range: [2**nBits-1, 2**nBits]
- I didn't implement (yet) the file format for the keypair. Mean that you can access access the key only from the struct

Warning: the keypair generated by this program aren't cryptographically secure !
My implementation is and only for a training purpose.
In consequence, do not use those keypairs for real life purpose !
*/


struct RSA_KEYPAIR {
    BIGNUM *public_modulus;         
    BIGNUM *public_exponent;      
    BIGNUM *private_exponent; 
    BIGNUM *p_factor;
    BIGNUM *q_factor;
    BIGNUM *crt_exp_one;     
    BIGNUM *crt_exp_sec;
};

/* ASN.1 type RSAPrivateKey
RSAPrivateKey ::= SEQUENCE {
    modulus         INTEGER, -- n
    publicExponent  INTEGER, -- e
    privateExponent INTEGER, -- d
    prime1          INTEGER, -- p
    prime2          INTEGER, -- q
    crt exponent1   INTEGER, -- d mod (p-1)
    crt exponent2   INTEGER, -- d mod (q-1)
*/



int consistency_test(struct RSA_KEYPAIR *kp_struct) {
    //This test verify that the generated keypair is valid by encrypting then decrypting a random message
    return RETURN_SUCCES;
}

int generate_private_exponent(struct RSA_KEYPAIR *kp_struct) {
    //Compute the inverse of e modular phi in order to obtain the private exponent d
    return RETURN_SUCCES;
}


int generate_primes_factors(struct RSA_KEYPAIR *kp_struct) {
    //Pickup two random number until they are both primes
    return RETURN_SUCCES;
}


int rsa_generation(int e, int key_size) {
    //main function that call the function that generate the keypair
    return RETURN_SUCCES;
}